name: BuildGo
env:
  FILE_NAME: 'hello-server'

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
  - cron: '*/15 * * * 1-6'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build Linux
        run: go build $FILE_NAME.go
      - name: Build windows
        run: env GOOS=windows GOARCH=amd64 go build $FILE_NAME.go
      - name: Upload artifact for linux
        uses: actions/upload-artifact@v1.0.0
        with:
          name: linux
          path: ./${{ env.FILE_NAME }}
      - name: Upload artifact for windows
        uses: actions/upload-artifact@v1.0.0
        with:
          name: windows
          path: ./${{ env.FILE_NAME }}.exe

  download-and-run-linux:
    name: teste
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: linux
          path: ./${{ env.FILE_NAME }}
        
