name: BuildGo
env:
  FILE_NAME: 'hello-server'

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build Linux
        run: go build $FILE_NAME.go
      - name: Build windows
        run: env GOOS=windows GOARCH=amd64 go build $FILE_NAME.go
      - name: Upload artifact for linux
          uses: actions/upload-artifact@v1.0.0
          with:
            name: linux
            path: ./${{ env.FILE_NAME }}
      - name: Upload artifact for windows
        uses: actions/upload-artifact@v1.0.0
        with:
          name: windows
          path: ./${{ env.FILE_NAME }}.exe